import React, { useState } from 'react';
import {
  Alert,
  Image,
  Modal,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { FoodLog } from '../types';
import { MacroRow } from './ui/MacroBadge';
import { Colors } from '../constants/Colors';

interface FoodLogCardProps {
  log: FoodLog;
  index?: number;
  onDelete: (id: string) => void;
}

function formatDateTime(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  }) + ' — ' + date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
}

export function FoodLogCard({ log, index = 0, onDelete }: FoodLogCardProps) {
  const [showPhotoModal, setShowPhotoModal] = useState(false);

  const handleDelete = () => {
    Alert.alert(
      'Delete Entry',
      `Are you sure you want to delete "${log.meal_name}"?`,
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Delete', style: 'destructive', onPress: () => onDelete(log.id) },
      ]
    );
  };

  const handlePhotoPress = () => {
    if (!log.photo_url) {
      router.push({ pathname: '/edit-entry/[id]', params: { id: log.id } });
      return;
    }
    Alert.alert(
      log.meal_name,
      undefined,
      [
        { text: 'View Full Screen', onPress: () => setShowPhotoModal(true) },
        { text: 'Replace Photo', onPress: () => router.push({ pathname: '/edit-entry/[id]', params: { id: log.id } }) },
        { text: 'Cancel', style: 'cancel' },
      ]
    );
  };

  return (
    <Animated.View entering={FadeInDown.delay(index * 60).springify()}>
      {log.photo_url && (
        <Modal
          visible={showPhotoModal}
          transparent
          animationType="fade"
          onRequestClose={() => setShowPhotoModal(false)}
          statusBarTranslucent
        >
          <View style={styles.photoModalOverlay}>
            <TouchableOpacity
              style={StyleSheet.absoluteFill}
              onPress={() => setShowPhotoModal(false)}
              activeOpacity={1}
            />
            <Image
              source={{ uri: log.photo_url }}
              style={styles.fullScreenPhoto}
              resizeMode="contain"
            />
            <TouchableOpacity
              style={styles.closePhotoBtn}
              onPress={() => setShowPhotoModal(false)}
            >
              <View style={styles.closePhotoBtnInner}>
                <Text style={styles.closePhotoBtnText}>✕</Text>
              </View>
            </TouchableOpacity>
          </View>
        </Modal>
      )}

      <View style={styles.card}>
        <TouchableOpacity onPress={handlePhotoPress} style={styles.photoContainer} testID="photo-container">
          {log.photo_url ? (
            <Image source={{ uri: log.photo_url }} style={styles.photo} />
          ) : (
            <View style={styles.photoPlaceholder}>
              <Text style={styles.photoEmoji}>🍽️</Text>
            </View>
          )}
        </TouchableOpacity>

        <View style={styles.content}>
          <View style={styles.header}>
            <Text style={styles.mealName} numberOfLines={1}>
              {log.meal_name}
            </Text>
            <View style={styles.actions}>
              <TouchableOpacity
                onPress={() =>
                  router.push({ pathname: '/edit-entry/[id]', params: { id: log.id } })
                }
                style={styles.actionBtn}
                testID="edit-btn"
              >
                <Ionicons name="pencil-outline" size={18} color={Colors.secondary} />
              </TouchableOpacity>
              <TouchableOpacity onPress={handleDelete} style={styles.actionBtn} testID="delete-btn">
                <Ionicons name="trash-outline" size={18} color={Colors.error} />
              </TouchableOpacity>
            </View>
          </View>

          <Text style={styles.dateTime}>{formatDateTime(log.logged_at)}</Text>

          <Text style={styles.calories}>
            {Math.round(log.calories)}{' '}
            <Text style={styles.calLabel}>cal</Text>
          </Text>

          <MacroRow
            protein={log.protein_g}
            carbs={log.carbs_g}
            fat={log.fat_g}
            fiber={log.fiber_g}
            size="sm"
          />

          {log.notes ? (
            <View style={styles.notesBox}>
              <Text style={styles.notesLabel}>📝 Notes</Text>
              <Text style={styles.notesText}>{log.notes}</Text>
            </View>
          ) : null}

          <Text style={styles.aiDisclaimer}>
            * Calorie estimate generated by AI — values are approximate.
          </Text>
        </View>
      </View>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderRadius: 16,
    marginBottom: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    gap: 12,
  },
  photoContainer: {
    alignSelf: 'flex-start',
  },
  photo: {
    width: 72,
    height: 72,
    borderRadius: 12,
  },
  photoPlaceholder: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: Colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoEmoji: { fontSize: 28 },
  content: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  mealName: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: Colors.text,
    flex: 1,
    marginRight: 8,
  },
  actions: { flexDirection: 'row', gap: 4 },
  actionBtn: { padding: 4 },
  dateTime: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: Colors.textLight,
    marginBottom: 4,
  },
  calories: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 22,
    color: Colors.primary,
    marginBottom: 6,
  },
  calLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: Colors.textLight,
  },
  notesBox: {
    marginTop: 8,
    backgroundColor: Colors.background,
    borderRadius: 8,
    padding: 8,
    borderLeftWidth: 3,
    borderLeftColor: Colors.secondary,
  },
  notesLabel: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 11,
    color: Colors.textLight,
    marginBottom: 2,
  },
  notesText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.text,
    lineHeight: 18,
  },
  aiDisclaimer: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 10,
    color: Colors.textMuted,
    marginTop: 6,
    fontStyle: 'italic',
  },
  photoModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullScreenPhoto: {
    width: '100%',
    height: '80%',
  },
  closePhotoBtn: {
    position: 'absolute',
    top: 52,
    right: 20,
  },
  closePhotoBtnInner: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  closePhotoBtnText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Nunito_700Bold',
  },
});
